name: Code Quality
run-name: ${{ github.actor }} is checking code quality 🔍
on:
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --all-extras --dev
        shell: bash

      - name: Run unit tests
        run: uv run pytest
        shell: bash
        #inter y eso para casa